@baseUrl = https://localhost:7178

###
GET {{baseUrl}}/balance

###
GET {{baseUrl}}/transactions

###
POST {{baseUrl}}/deposit
Content-Type: application/json

{
  "value": 800.0
}

###
POST {{baseUrl}}/withdraw
Content-Type: application/json

{
  "value": 20
}