@baseUrl = https://localhost:7214

###
GET {{baseUrl}}/baskets

###
POST {{baseUrl}}/baskets
Content-Type: application/json

[
  { "productId": 1, "quantity": 2 },
  { "productId": 2, "quantity": 1 },
  { "productId": 3, "quantity": 1 },
  { "productId": 4, "quantity": 1 },
  { "productId": 5, "quantity": 1 },
  { "productId": 6, "quantity": 1 },
  { "productId": 7, "quantity": 1 },
  { "productId": 8, "quantity": 1 }
]

###
GET {{baseUrl}}/checkouts

###
POST {{baseUrl}}/checkouts